name: Build
on: [commit, push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Run OX Security Scan to check for vulnerabilities
        with:
          ox_api_key: ${{ secrets.OX_API_KEY }}
        uses: oxsecurity/ox-security-scan@main
      
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

#      - name: Build the image multiplatform
#        run: docker buildx build --output "type=image,push=false" --secret id=github_token,src=${{ secrets.GH_FINEGRAINED_TOKEN }} --platform linux/amd64,linux/arm64 --tag aaronhmiller/oxswagger:latest --file ./Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aaronhmiller/oxswagger:latest
          secrets: |
            "github_token=${{ secrets.GH_FINEGRAINED_TOKEN }}"
          platforms: linux/amd64,linux/arm64
